// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyVersion("2023.1.6.178")]
[assembly: AssemblyFileVersion("2023.1.6.178")]
